### ISSUE TITLE
You're a dipshit.

### ISSUE THREAD

**Issue by Quest79** [matiffeder/3DS-stuff#9]
Put this batch in a folder with a bunch of files and games. Ran it and put in one of the games it suggested "0004000000040a00". It didnt do much and I close it. 

It then proceeds to delete EVERYTHING in the directory, including itself. 

Nice bit of code. Are you stupid or just malicious? Glad I have backups.

**Comment by matiffeder** [comment]
As you can see in the code, it will not delete all the files. Moreover, it can not work by itself. I will also never put an explanation on how to use it. This is not for people to use. This is for sharing code with people who like coding.
